- name: Simple SFTP
  # You may pin to the exact commit or the version.
  # uses: Atyn/simple-sftp-action@a684a17fdd2b79d23101d568d9e8b5070f58e685
  uses: Atyn/simple-sftp-action@0.0.2
  with:
    # URL to the SFTP server. Example: sftp://USERNAME:PASSWORD@example.com/remote-directory
    url: # optional
    # The directory that should be uploaded
    localdir: # optional
    
    - name: Simple commit
  # You may pin to the exact commit or the version.
  # uses: zwaldowski/git-commit-action@66730766679672410dc04830ae6389f4376c8c94
  uses: zwaldowski/git-commit-action@v1
  with:
    # Directory to create commit in
    working_directory: # optional, default is .
    # Commit message
    commit_message: # default is Automated commit
    # Name to use for commit author
    author_name: # optional, default is GitHub Actions
    # Email to use for commit author
    author_email: # optional, default is actions@github.com
